include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    avoid_web_libraries_in_flutter: ignore
    no_logic_in_create_state: ignore
    use_build_context_synchronously: ignore
  exclude:
    - lib/generated/**
    - lib/**/*.g.dart
    - script/**/*.g.dart
    - lib/generated_plugin_registrant.dart
    - script/**
  language:
    strict-casts: true
    strict-raw-types: true

linter:
  rules:
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - always_use_package_imports
    - annotate_overrides
    - avoid_bool_literals_in_conditional_expressions
    - avoid_catches_without_on_clauses
    - avoid_empty_else
    - avoid_init_to_null
    - avoid_print
    - avoid_relative_lib_imports
    - avoid_return_types_on_setters
    - avoid_returning_null_for_void
    - avoid_single_cascade_in_expression_statements
    - avoid_slow_async_io
    - avoid_types_as_parameter_names
    - avoid_unnecessary_containers
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - await_only_futures
    - camel_case_extensions
    - camel_case_types
    - cancel_subscriptions
    - collection_methods_unrelated_type
    - control_flow_in_finally
    - curly_braces_in_flow_control_structures
    - empty_catches
    - empty_constructor_bodies
    - empty_statements
    - exhaustive_cases
    - flutter_style_todos
    - implementation_imports
    - library_prefixes
    - no_duplicate_case_values
    - package_prefixed_library_names
    - prefer_asserts_in_initializer_lists
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_final_fields
    - prefer_if_null_operators
    - prefer_initializing_formals
    - prefer_inlined_adds
    - prefer_single_quotes
    - prefer_void_to_null
    - require_trailing_commas
    - unawaited_futures
    - unnecessary_const
    - unnecessary_getters_setters
    - unnecessary_new
    - unnecessary_overrides
    - unnecessary_statements
    - unnecessary_string_escapes
    - unnecessary_string_interpolations
    - unnecessary_this
    - unrelated_type_equality_checks
    - use_full_hex_values_for_flutter_colors
    - use_rethrow_when_possible
    - valid_regexps
    - void_checks
